version: "3.7"

services:

  rstudio:
    image: "rocker/tidyverse:${TIDYVERSE_TAG}"
    build: 
      context: .
      args:
        TIDYVERSE_TAG: $TIDYVERSE_TAG
        CONDA_VERSION: $CONDA_VERSION
        CONDA_PATH: $CONDA_PATH
        